version: 0.2

phases:
  pre_build:
    commands:
      - echo Pre-Build started on `date`
      - mvn clean
  build:
    commands:
      - echo "Build started on `date`"
      - mvn clean package
  post_build:
    commands:
      - echo post Build completed on `date`

artifacts:
  files:
    - target/course-list-lambda*
